version: '3.7'

services:
    web:
        build: .
        command: python /django-heroku-staticfiles/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django-heroku-staticfiles
        ports:
            - 8000:8000
